### ISSUE TITLE
Allow authentication in multiple registries

### ISSUE THREAD

**Issue by itasahobby** [prefapp/firestarter-workflows#10]
# Motivation

At the moment the workflow only allows to push to azure registry. It could be of interest to allow other registries like GitHub or DockerHub.

## Assumptions

* Registry login is performed at the python level. 
* We'll use the provider SDKs to perform the docker login. 

# Acceptance criteria

- [ ] Multiple registries are allowed
- [ ] Team acceptance

**Comment by frmadem** [comment]
Registry login should be performed at the python level. 

1. We need machinery to login in a specific kind of registry. 
2. Can we login in different registries at the same time? Do we need to login sequentially (i.e registryN1 -> push, registryN2 -> push...)
3. Do we need to install all the machinery for all the supported registries even if we don't use it in a particular case?

**Comment by itasahobby** [comment]
We should login first in all registries. Therefore if any of them fails the workflow stops, avoiding situations where some of the images were published before the whole workflow fails.

**Comment by itasahobby** [comment]
List of registries that should be considered to support:
* DockerHub
* Azure Container Registry
* Google Container Registry
* Amazon ECR
* GitHub Container Registry

**Comment by alambike** [comment]
Related to https://github.com/prefapp/features/issues/149

**Comment by alambike** [comment]
@itasahobby I reopen this too until add support for ACR with Azure OIDC

**Comment by alambike** [comment]
Closed by #31
