### ISSUE TITLE
[FEAT] Add AJV validation to `build_images.yaml` config file

### ISSUE THREAD

**Issue by juanjosevazquezgil** [prefapp/firestarter-workflows#124]
# Motivation
While AJV can't be used to validate everything we want within a `build_images.yaml` file, it can still be used to validate that some of the data is valid and coherent. Namely:

- Both `snapshots` and `releases` exist as global level keys, and no other key does. Maybe check that each have at least a single declared flavor too?
- If a flavor exists under any of those two keys, it:
     1.  Must contain the `dockerfile` key, with a valid path as a value 
     2. Can contain the `auto` key, and if it does it must be a valid boolean value
     3. Can contain the `build_args` and/or `secrets` keys, and if either or both are contained they must be objects with any number of keys, each of which can have any type of value
     4. Can contain the `extra_registries` key, and if it does it must be a list of objects with the following keys:
          > `name`: a string
          > `repository`: a string
          > `auth_strategy`: a string, but must match one of the avaliable `auth_strategy` values (`azure_oidc`, `aws_oidc`, etc)

While this isn't  really crucial to the feature's usage, it's still a nice validation to have to ensure neither us nor our customer make any avoidable mistakes while configuring our app.

### Acceptance criteria
- [ ] The AJV schema is created and meets the requirements described above
- [ ] The validation is made at some point (ideally when changes are made to the file on Github)
- [ ] Team acceptance

**Comment by alambike** [comment]
In Python, instead of AJV we should use [python-jsonschema](https://python-jsonschema.readthedocs.io/en/stable/validate/#).
