### ISSUE TITLE
OIDC auth in CI workflow

### ISSUE THREAD

**Issue by alambike** [prefapp/firestarter-workflows#34]
### Motivation
We need to authenticate in the org registries, to the CI workflow be able to use images from private registries

### Acceptance criteria
- [x] Common logic implemented in https://github.com/prefapp/firestarter-workflows/pull/31 & https://github.com/prefapp/firestarter-workflows/pull/30 moved to common module, instead of build-images
- [x] CI workflow allowed to pull images from org registries with OIDC

**Comment by jalvarezit** [comment]
@alambike I was waiting for [this PR](https://github.com/prefapp/tfm/pull/25) to be approved but we can close it since is not directly specified in the acceptance criteria
