### ISSUE TITLE
[FIX] Update dagger to 0.8 - BREAKING CHANGES!

### ISSUE THREAD

**Issue by alambike** [prefapp/firestarter-workflows#37]
### Motivation
We want to update the firestarter-workflows to the new 0.8.4 python sdk version
https://github.com/dagger/dagger/releases

:warning: 
There are breaking changes:
https://dagger.io/blog/dagger-0-8

### Acceptance criteria
- [ ] Workflows updated to latest 0.8 version
- [ ] Tests passing

**Comment by jalvarezit** [comment]
We should also update pyyaml
![imagen](https://github.com/prefapp/firestarter-workflows/assets/47305925/87070fc5-63ac-42d4-a68b-b090282174c5)

This error get's fixed in 6.0.1

**Comment by jalvarezit** [comment]
Once merged we need to update [test-repo-rundagger](https://github.com/prefapp/test-repo-rundagger/)
