### ISSUE TITLE
Allow receiving input data from environment variables

### ISSUE THREAD

**Issue by itasahobby** [prefapp/firestarter-workflows#6]
# Motivation

To avoid having to deal with nested quotes we could use github action INPUT environment variables.

# Acceptance criteria

- [ ] Both cli arguments and environment variables formats are supported
- [ ] Team acceptance

**Comment by itasahobby** [comment]
Related to https://github.com/prefapp/run-dagger-py/pull/2

**Comment by alambike** [comment]
Closed by https://github.com/prefapp/firestarter-workflows/pull/7 and https://github.com/prefapp/firestarter-workflows/pull/8
